# Generated by Django 2.0.5 on 2018-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'sort feature',
            },
        ),
        migrations.CreateModel(
            name='mobile_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_companny', models.CharField(max_length=200, null=True)),
                ('mobile_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('rating', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'mobile_phone',
            },
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Weight', models.CharField(max_length=100, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Size', models.CharField(max_length=300, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=300, null=True)),
                ('image_path', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'phone',
            },
        ),
        migrations.CreateModel(
            name='samsung_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('Size', models.FloatField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('imagepath1', models.CharField(max_length=300, null=True)),
                ('imagepath2', models.CharField(max_length=300, null=True)),
                ('battery', models.CharField(max_length=400, null=True)),
                ('back_camera', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'samsungphone',
            },
        ),
        migrations.CreateModel(
            name='signup_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300, null=True)),
                ('role', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sort_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(null=True)),
                ('sh_hd', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'sort feature',
            },
        ),
    ]
