# Generated by Django 2.0.5 on 2018-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_blog_feature_mobile_phone_phone_samsung_phone_signup_table_sort_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort_feature',
            name='f_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sort_feature',
            name='roles',
            field=models.IntegerField(null=True),
        ),
    ]
